# Generated by Django 3.0.8 on 2020-07-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название категории')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='уровень владения языком')),
                ('code', models.CharField(max_length=2, verbose_name='код уровня владения языком')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название темы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='слово')),
                ('translate', models.CharField(max_length=255, verbose_name='перевод')),
                ('transcription', models.CharField(max_length=255, verbose_name='транскрипция')),
                ('example', models.CharField(max_length=255, verbose_name='пример употребления слова')),
                ('sound', models.FileField(blank=True, upload_to='sounds/', verbose_name='произношение слова')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Theme')),
            ],
        ),
    ]
